---
deployment:
  tasks:
    - export DEPLOYPATH=/home/seleaddv/public_html/
    - /bin/cp "index.html" $DEPLOYPATH
    - /bin/cp "404.html" $DEPLOYPATH
    - /bin/cp "ashen-hearth.html" $DEPLOYPATH
    - /bin/cp "content-notes.html" $DEPLOYPATH
    - /bin/cp "links.html" $DEPLOYPATH
    - /bin/cp "monstrous-beloved.html" $DEPLOYPATH
    - /bin/cp "press.html" $DEPLOYPATH
    - /bin/cp "privacy.html" $DEPLOYPATH
    - /bin/cp "reading-order.html" $DEPLOYPATH
    - /bin/cp "songs-of-eidmor.html" $DEPLOYPATH
    - /bin/cp "robots.txt" $DEPLOYPATH
    - /bin/cp "sitemap.xml" $DEPLOYPATH
    - /bin/cp "books.json" $DEPLOYPATH
    - /bin/cp "series.json" $DEPLOYPATH
    - /bin/cp "Night's Own KU Cover.png" $DEPLOYPATH
    - /bin/cp "Night_s_Own_KU_Cover.png" $DEPLOYPATH
    - /bin/cp "Selena_Monroe_Logo_Transparent.png" $DEPLOYPATH
    - /bin/cp "Selena_Monroe_Profile_Pic.png" $DEPLOYPATH
    - /bin/cp "The_Binding_Night.png" $DEPLOYPATH
    - /bin/cp "The_Tide_Keeps_KU_v3.jpg" $DEPLOYPATH
    - /bin/cp "The_Turning_Season_KU.png" $DEPLOYPATH
    - /bin/cp "the_vast_and_particular_ku_cover.png" $DEPLOYPATH
    - /bin/cp "Website_Banner.png" $DEPLOYPATH
    - /bin/cp "The_Turning_Season_home.jpg" $DEPLOYPATH
    - /bin/cp "the_vast_and_particular_home.jpg" $DEPLOYPATH
    - /bin/cp "Night_s_Own_KU_Cover_home.jpg" $DEPLOYPATH
    - /bin/cp "The_Tide_Keeps_home.jpg" $DEPLOYPATH
    - /bin/cp "The_Binding_Night_home.jpg" $DEPLOYPATH
    - /bin/cp "What_the_Night_Keeps_home.jpg" $DEPLOYPATH
    - /bin/cp "What_the_Night_Keeps_KU_Cover.jpg" $DEPLOYPATH
    - /bin/cp "The_Turning_Season_KU_v2.jpg" $DEPLOYPATH
    - /bin/cp "the_vast_and_particular_ku_cover_v2.jpg" $DEPLOYPATH
    - /bin/cp "Night_s_Own_KU_Cover_v2.jpg" $DEPLOYPATH
    - /bin/cp "The_Tide_Keeps_KU_v4.jpg" $DEPLOYPATH
    - /bin/cp "The_Binding_Night_v2.jpg" $DEPLOYPATH
    - /bin/cp "Website_Banner_web.jpg" $DEPLOYPATH
    - /bin/cp "Selena_Monroe_Profile_Pic_web.jpg" $DEPLOYPATH
    - /bin/cp "Selena_Monroe_Logo_Transparent_256.png" $DEPLOYPATH
